version: '3.7'

services:
  
  db:
    container_name: blogrestapi_db
    image: postgres:13.0-alpine
    build:
      context: ./postgres
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./app/blogapi/.env.prod.db
 
volumes:
  postgres_data: