version: '3.7'

services:
  web:
    container_name: blogrestapi_site_web
    build: 
      context: ./app
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8100:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    container_name: blogrestapi_site_db
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dockblogrestapisite

volumes:
  postgres_data: