version: '3.7'

services:
  web:
    container_name: blogrestapi_prod_web
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn blogapi.wsgi:application --bind 0.0.0.0:8000
    volumes: 
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8500:8000
    env_file:
      - ./app/blogapi/.env.prod
    depends_on:
      - db
  db:
    container_name: blogrestapi_db
    image: postgres:13.0-alpine
    build:
      context: ./postgres
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./app/blogapi/.env.prod.db
 
  nginx:
    container_name: blogrestapi_nginx
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: