# Generated by Django 3.2.19 on 2023-08-13 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosyndic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='fichier',
            new_name='jfile',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='libelle',
            new_name='title',
        ),
    ]
