# Generated by Django 3.2.19 on 2023-08-21 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prosyndic', '0003_alter_incident_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.SmallIntegerField()),
                ('nb_appartement', models.SmallIntegerField()),
                ('photo', models.ImageField(upload_to='media/')),
            ],
            options={
                'verbose_name': 'Lot',
                'ordering': ('numero',),
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='jfile',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['content_type', 'object_id'], name='prosyndic_d_content_b916c4_idx'),
        ),
        migrations.AddField(
            model_name='lot',
            name='residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prosyndic.residence'),
        ),
    ]
