# Generated by Django 4.2 on 2023-05-02 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogapi',
            old_name='created',
            new_name='created_at',
        ),
    ]
